version: '2'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1

services:
    db:
        build: src/db
        image: omadonex/laravel_db:1.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - internal
        ports:
            - "${PORT_DB}:3306"
        restart: always
        volumes:
            - ./data/mysql:/var/lib/mysql
    app:
        mem_limit: 1024m
        memswap_limit: 2048m
        mem_reservation: 512m
        privileged: true
        build:
            context: src/app
            args:
                - IMAGICK=${IMAGICK}
                - XDEBUG=${XDEBUG}
                - VERSION_XDEBUG=${VERSION_XDEBUG}
                - VERSION_PHP=${VERSION_PHP}
                - VERSION_NVM=${VERSION_NVM}
                - VERSION_NODE=${VERSION_NODE}
        image: omadonex/laravel_app:1.2
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - db
        networks:
            - internal
        restart: always
        volumes:
            - ${PROJECT_PATH}:/var/www
            - ./src/app/www.conf:/usr/local/etc/php-fpm.d/www.conf
    nginx:
        build: src/nginx
        image: omadonex/laravel_nginx:1.0
        networks:
            - internal
        ports:
            - "${PORT_HTTP}:80"
            - "${PORT_HTTPS}:443"
        restart: always
        volumes_from:
            - app
        volumes:
            - ./temp/nginx/logs:/var/log/nginx
    pma:
        build: src/pma
        image: omadonex/laravel_pma:1.0
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        depends_on:
            - db
        networks:
            - internal
        ports:
            - "${PORT_PMA}:80"
        restart: always